#!/usr/bin/env python3
"""
DISCRETUM — Final paper figures for the 4D v3 campaign.

Generates all figures referenced in paper/discretum.tex:
  fig6_scaling_dH.png        — already generated by extrapolation.py
  fig9_spectral_multiscale.png — already generated by spectral_multiscale_plot.py
  fig_connectivity.png       — already generated by extrapolation.py

New figures generated here:
  fig1_convergence_4d.png    — CMA-ES vs GA fitness convergence
  fig2_scaling_all.png       — Combined d_H, d_s, kappa scaling with baselines
  fig3_rule_summary.png      — Best rule topology balance + evolved vs bare comparison
"""
import json
import os
import numpy as np

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 9,
    'axes.labelsize': 10,
    'axes.titlesize': 10,
    'legend.fontsize': 7,
    'xtick.labelsize': 8,
    'ytick.labelsize': 8,
    'figure.dpi': 300,
    'savefig.dpi': 300,
    'savefig.bbox': 'tight',
    'text.usetex': False,
    'axes.linewidth': 0.6,
    'lines.linewidth': 1.0,
    'lines.markersize': 4,
})

FIGDIR = 'paper/figures'
COL_WIDTH = 3.375
os.makedirs(FIGDIR, exist_ok=True)


def load_json(path):
    with open(path) as f:
        return json.load(f)


def stats_from_connected(data):
    runs = data.get('runs', [])
    conn = [r for r in runs if not r.get('aborted') and r.get('is_connected')]
    if not conn:
        return None
    def s(key):
        v = np.array([r[key] for r in conn])
        return float(np.mean(v)), float(np.std(v, ddof=1)/np.sqrt(len(v))) if len(v) > 1 else 0.0
    return {k: s(k) for k in ['d_H', 'd_s', 'mean_curvature', 'mean_degree', 'n_final']}, len(conn)


def stats_from_all(data):
    runs = data.get('runs', [])
    valid = [r for r in runs if not r.get('aborted')]
    if not valid:
        return None
    def s(key):
        v = np.array([r[key] for r in valid])
        return float(np.mean(v)), float(np.std(v, ddof=1)/np.sqrt(len(v))) if len(v) > 1 else 0.0
    return {k: s(k) for k in ['d_H', 'd_s', 'mean_curvature', 'mean_degree', 'n_final']}, len(valid)


# ─── Fig 1: Convergence ───
def fig1_convergence():
    """CMA-ES and GA fitness convergence curves."""
    cmaes_path = 'data/checkpoints/4d_v3_cmaes/cmaes_result.json'
    ga_path = 'checkpoints/4d_v3_ga/ga_result.json'

    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.5))

    if os.path.exists(cmaes_path):
        d = load_json(cmaes_path)
        hist = d.get('fitness_history', [])
        if hist:
            ax.plot(range(len(hist)), hist, 'b-', lw=0.8, label=f'CMA-ES (best={d["best_fitness"]:.3f})')

    if os.path.exists(ga_path):
        d = load_json(ga_path)
        hist = d.get('fitness_history', [])
        if hist:
            ax.plot(range(len(hist)), hist, 'r-', lw=0.8, alpha=0.7, label=f'GA (best={d["best_fitness"]:.3f})')

    ax.set_xlabel('Generation')
    ax.set_ylabel('Best fitness')
    ax.set_title('4D v3 campaign convergence')
    ax.legend(loc='lower right')
    ax.grid(True, alpha=0.2)
    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig1_convergence_4d.png'))
    fig.savefig(os.path.join(FIGDIR, 'fig1_convergence_4d.pdf'))
    plt.close()
    print("  fig1_convergence_4d")


# ─── Fig 2: Combined 4-panel scaling (evolved + baseline + connectivity) ───
def fig2_scaling_all():
    """Four-panel scaling plot: d_H, d_s, kappa, connected fraction."""
    SCALES = [4, 5, 6, 7, 8]

    evolved, baseline = {}, {}
    for L in SCALES:
        ep = f'data/results/scaling_4d_v3/evolved_L{L}.json'
        bp = f'data/results/scaling_4d_v3/baseline_L{L}.json'
        if os.path.exists(ep):
            evolved[L] = load_json(ep)
        if os.path.exists(bp):
            baseline[L] = load_json(bp)

    fig, axes = plt.subplots(2, 2, figsize=(COL_WIDTH * 2, 4.5), sharex=True)

    obs_list = [
        ('d_H', '$d_H$', 4.0),
        ('d_s', '$d_s$', 4.0),
        ('mean_curvature', r'$\langle\kappa\rangle$', 0.0),
    ]

    panel_labels = ['(a)', '(b)', '(c)', '(d)']
    flat_axes = [axes[0, 0], axes[0, 1], axes[1, 0], axes[1, 1]]

    for idx, (key, ylabel, target) in enumerate(obs_list):
        ax = flat_axes[idx]

        # Evolved (connected only)
        N_e, y_e, ye_e = [], [], []
        for L in SCALES:
            if L not in evolved:
                continue
            cs, nc = stats_from_connected(evolved[L]) or (None, 0)
            if cs is None or nc < 1:
                continue
            N_e.append(L**4)
            y_e.append(cs[key][0])
            ye_e.append(cs[key][1])

        # Baseline (all runs, always connected)
        N_b, y_b, ye_b = [], [], []
        for L in SCALES:
            if L not in baseline:
                continue
            bs, nb = stats_from_all(baseline[L]) or (None, 0)
            if bs is None:
                continue
            N_b.append(L**4)
            y_b.append(bs[key][0])
            ye_b.append(bs[key][1])

        if N_e:
            ax.errorbar(N_e, y_e, yerr=ye_e, fmt='bo-', ms=4, capsize=2, lw=1.0, label='Evolved (conn.)')
        if N_b:
            ax.errorbar(N_b, y_b, yerr=ye_b, fmt='ks--', ms=3, capsize=2, lw=0.6, alpha=0.6, label='Bare lattice')

        ax.axhline(target, color='gray', ls=':', lw=0.4, alpha=0.6)
        ax.set_ylabel(ylabel)
        ax.set_xscale('log')
        ax.legend(fontsize=6, loc='best')
        ax.grid(True, alpha=0.15)
        ax.set_title(f'{panel_labels[idx]} {ylabel}', fontsize=9)

    # Panel (d): Connected fraction
    ax = flat_axes[3]
    N_vals, conn_frac = [], []
    for L in SCALES:
        if L not in evolved:
            continue
        d = evolved[L]
        runs = [r for r in d.get('runs', []) if not r.get('aborted')]
        conn = [r for r in runs if r.get('is_connected')]
        N_vals.append(L**4)
        conn_frac.append(100 * len(conn) / max(len(runs), 1))

    ax.bar(range(len(N_vals)), conn_frac,
           tick_label=[str(n) for n in N_vals],
           color='steelblue', alpha=0.8, edgecolor='white', lw=0.5)
    ax.axhline(100, color='gray', ls=':', lw=0.4, alpha=0.6)
    ax.set_ylabel('Connected (%)')
    ax.set_ylim(0, 115)
    ax.set_title(f'{panel_labels[3]} Connected fraction', fontsize=9)
    ax.grid(True, axis='y', alpha=0.15)
    for i, (n, c) in enumerate(zip(N_vals, conn_frac)):
        ax.text(i, c + 3, f'{c:.0f}%', ha='center', va='bottom', fontsize=7)

    # Common x-label on bottom row
    for ax in [axes[1, 0], axes[1, 1]]:
        ax.set_xlabel('$N_0 = L^4$')

    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig2_scaling_all.png'))
    fig.savefig(os.path.join(FIGDIR, 'fig2_scaling_all.pdf'))
    plt.close()
    print("  fig2_scaling_all (4-panel with connectivity)")


# ─── Fig 3: Rule summary ───
def fig3_rule_summary():
    """Best rule topology balance + connectivity vs scale."""
    rule = load_json('data/results/best_rule_4d_v3.json')
    topo = rule.get('topological_probabilities', {})
    names = ['p_add', 'p_rem', 'p_rew', 'p_spl', 'p_mrg']
    probs = [topo.get(n, 0) for n in names]

    fig, axes = plt.subplots(1, 2, figsize=(COL_WIDTH * 2, 2.5))

    # (a) Topology balance
    ax = axes[0]
    colors = ['#2196F3', '#F44336', '#FF9800', '#4CAF50', '#9C27B0']
    labels = ['Add', 'Remove', 'Rewire', 'Split', 'Merge']
    bars = ax.bar(labels, probs, color=colors, alpha=0.8, edgecolor='white', lw=0.5)
    ax.set_ylabel('Probability')
    ax.set_title('(a) Topological move probabilities')
    for bar, p in zip(bars, probs):
        if p > 0.01:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                    f'{p:.3f}', ha='center', va='bottom', fontsize=7)
    ax.set_ylim(0, max(max(probs) * 1.3, 0.05))

    # (b) Connectivity vs scale
    ax = axes[1]
    SCALES = [4, 5, 6, 7, 8]
    N_vals = [L**4 for L in SCALES]
    conn_frac = []
    for L in SCALES:
        ep = f'data/results/scaling_4d_v3/evolved_L{L}.json'
        if os.path.exists(ep):
            d = load_json(ep)
            runs = [r for r in d.get('runs', []) if not r.get('aborted')]
            conn = [r for r in runs if r.get('is_connected')]
            conn_frac.append(100 * len(conn) / max(len(runs), 1))
        else:
            conn_frac.append(0)

    ax.plot(N_vals, conn_frac, 'ro-', ms=5, lw=1.2)
    ax.fill_between(N_vals, 0, conn_frac, alpha=0.1, color='red')
    ax.set_xlabel('$N = L^4$')
    ax.set_ylabel('Connected (%)')
    ax.set_xscale('log')
    ax.set_ylim(-5, 110)
    ax.set_title('(b) Connectivity vs scale')
    ax.grid(True, alpha=0.2)
    for L, N, c in zip(SCALES, N_vals, conn_frac):
        ax.annotate(f'L={L}', (N, c), textcoords='offset points',
                    xytext=(5, 5), fontsize=6)

    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig3_rule_summary.png'))
    fig.savefig(os.path.join(FIGDIR, 'fig3_rule_summary.pdf'))
    plt.close()
    print("  fig3_rule_summary")


# ─── Fig 4: Baseline validation ───
def fig4_baseline_validation():
    """Bare lattice d_H vs expected dimension 4."""
    SCALES = [4, 5, 6, 7, 8]
    N_vals, dH_vals, dH_errs = [], [], []

    for L in SCALES:
        bp = f'data/results/scaling_4d_v3/baseline_L{L}.json'
        if not os.path.exists(bp):
            continue
        d = load_json(bp)
        bs, _ = stats_from_all(d) or (None, 0)
        if bs is None:
            continue
        N_vals.append(L**4)
        dH_vals.append(bs['d_H'][0])
        dH_errs.append(bs['d_H'][1])

    fig, ax = plt.subplots(figsize=(COL_WIDTH, 2.2))
    ax.errorbar(N_vals, dH_vals, yerr=dH_errs, fmt='ko-', ms=4, capsize=2)
    ax.axhline(4.0, color='gray', ls=':', lw=0.5, label='$d = 4$ (expected)')
    ax.set_xlabel('$N$')
    ax.set_ylabel('$d_H$ (bare lattice)')
    ax.set_xscale('log')
    ax.set_title('Bare lattice Hausdorff dim. validation')
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.2)
    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig4_baseline_dH.png'))
    fig.savefig(os.path.join(FIGDIR, 'fig4_baseline_dH.pdf'))
    plt.close()
    print("  fig4_baseline_dH")


# ─── Fig 5: Ensemble distribution at L=5 ───
def fig5_ensemble_distributions():
    """Distribution of d_H and kappa across 20 runs at L=5."""
    ep = 'data/results/scaling_4d_v3/evolved_L5.json'
    if not os.path.exists(ep):
        print("  fig5 SKIPPED (no L=5 data)")
        return

    d = load_json(ep)
    runs = d.get('runs', [])
    conn = [r for r in runs if not r.get('aborted') and r.get('is_connected')]
    disc = [r for r in runs if not r.get('aborted') and not r.get('is_connected')]

    fig, axes = plt.subplots(1, 2, figsize=(COL_WIDTH * 2, 2.2))

    # (a) d_H distribution
    ax = axes[0]
    if conn:
        dH_conn = [r['d_H'] for r in conn]
        ax.hist(dH_conn, bins=12, color='steelblue', alpha=0.7, edgecolor='white', label=f'Connected ({len(conn)})')
    if disc:
        dH_disc = [r['d_H'] for r in disc]
        ax.hist(dH_disc, bins=5, color='red', alpha=0.5, edgecolor='white', label=f'Disconnected ({len(disc)})')
    ax.set_xlabel('$d_H$')
    ax.set_ylabel('Count')
    ax.set_title(f'(a) Hausdorff dimension (L=5, N=625)')
    ax.legend(fontsize=6)

    # (b) kappa distribution
    ax = axes[1]
    if conn:
        kappa_conn = [r['mean_curvature'] for r in conn]
        ax.hist(kappa_conn, bins=12, color='steelblue', alpha=0.7, edgecolor='white', label=f'Connected ({len(conn)})')
    if disc:
        kappa_disc = [r['mean_curvature'] for r in disc]
        ax.hist(kappa_disc, bins=5, color='red', alpha=0.5, edgecolor='white', label=f'Disconnected ({len(disc)})')
    ax.set_xlabel(r'$\langle\kappa\rangle$')
    ax.set_ylabel('Count')
    ax.set_title(f'(b) Mean curvature (L=5, N=625)')
    ax.legend(fontsize=6)

    fig.tight_layout()
    fig.savefig(os.path.join(FIGDIR, 'fig5_ensemble_L5.png'))
    fig.savefig(os.path.join(FIGDIR, 'fig5_ensemble_L5.pdf'))
    plt.close()
    print("  fig5_ensemble_L5")


def main():
    print("Generating final paper figures...")
    fig1_convergence()
    fig2_scaling_all()
    fig3_rule_summary()
    fig4_baseline_validation()
    fig5_ensemble_distributions()
    print(f"\nAll figures saved to {FIGDIR}/")

    # List all figures
    figs = sorted([f for f in os.listdir(FIGDIR) if f.endswith('.png')])
    print(f"\nFigures ({len(figs)} PNG):")
    for f in figs:
        print(f"  {f}")


if __name__ == '__main__':
    main()
